### ISSUE TITLE
[supervisor.docker.addon] Invalid build environment, can't build this add-on!

### ISSUE THREAD

**Issue by dorinvlas** [Dattel/homeassistant-influxdb2#1]
Hi Dan, 
I wanted to give a try to this addon from your repository. I already have influxdb 1.7 addon from Frank, running for a few years. But I would like to think that v2 is possible right now.

When I am trying to install the addon from your repository on my HA VM running in proxmox, I get this error.
23-05-11 13:15:18 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/50fa1dca_influxdb2
23-05-11 13:15:18 ERROR (SyncWorker_1) [supervisor.docker.addon] Invalid build environment, can't build this add-on!

I thought it may be because of influxdb2/build.yaml. 
My HA hardware says: Virtual Machine, ova.

Thanks for your contributions.

**Comment by Dattel** [comment]
Hi,
since this i my first containered addon i'm not sure, if i can assist you in a approbiate way. But let's have a try.
What kind of kernel architecture is your current operating system?

Currently i think, the container is only usable for amd64 and i need to change it.. :-D

**Comment by dorinvlas** [comment]
its running inside proxmox as a Virtual Machine.
![image](https://github.com/Dattel/homeassistant-influxdb2/assets/13332461/1ad82c02-2dc9-46b0-9823-b4f7160997cc)

**Comment by dorinvlas** [comment]
![image](https://github.com/Dattel/homeassistant-influxdb2/assets/13332461/3cb31940-afc9-4f1a-9c33-8669b3d1a2ed)

**Comment by dorinvlas** [comment]
According to proxmox and Intel, q35 means:

The Intel® 3 Series Chipsets are designed for use with the Intel® Core™2 Duo desktop
processor and Intel® Core™2 Quad processor based platforms. Each chipset contains
two components: GMCH (or MCH) for the host bridge and I/O Controller Hub 9 (ICH9)
for the I/O subsystem. The 82Q33 GMCH is part of the Intel® Q35 Express chipset.
The 82Q33 GMCH is part of the Intel® Q33 Express chipset. The 82G33 GMCH is part
of the Intel® G33 Express chipset. The 82P35 MCH is part of the Intel® P35 Express
chipset. The ICH9 is the ninth generation I/O Controller Hub and provides a multitude
of I/O related functions. The following figures show example system block diagrams
for the Intel® Q35, Q33, G33 and P35 Express chipsets.

**Comment by Dattel** [comment]
yes... that's fine... what kind of Homeassistant kernel-architecture are you using?

When you got access to a ssh console type `uname -m`
For me it's x86_64

**Comment by dorinvlas** [comment]
I believe if you add the following to your config.yaml, because i386 is already defined in your build.yaml
```
arch:
  - i386
````
Check frenchk version https://github.com/hassio-addons/addon-influxdb/blob/main/influxdb/config.yaml

**Comment by Dattel** [comment]
added these option for you.. would you be so kind and test the latest version?

**Comment by dorinvlas** [comment]
probably it has to be updated in the [Repository/config.yaml](https://github.com/Dattel/repository/blob/main/influxdb2/config.yaml) also

**Comment by Dattel** [comment]
thx... but that's just for completeness.. it was not required for me to update the addon in homeassistant... maybe you need to trigger the UpdateCheck manual

Homeassistant ->Settings->addons->add-on Store -> the three points at the top: Check for Updates

**Comment by dorinvlas** [comment]
Tried that... got some errors in the logs of supervisor, now addon page is not loading anymore...
![image](https://github.com/Dattel/homeassistant-influxdb2/assets/13332461/7db6bde6-2fc6-4fd0-8668-152ea4009543)

**Comment by Dattel** [comment]
but the exception is coming from the bitwarden addon...  and the yellow message from scrutiny addon..

**Comment by Dattel** [comment]
the addon will take a while to build and start up complete... maybe be a bit more patient?

**Comment by dorinvlas** [comment]
![image](https://github.com/Dattel/homeassistant-influxdb2/assets/13332461/49753a47-c0f9-41df-b5d1-db95dabaf996)

**Comment by Dattel** [comment]
yes... i see.. 

that's because the required influx.deb does not exist on the influx source.
the docker file builds a path to download the required deb package to create the addon local

currently the installer tries to download:
https://dl.influxdata.com/influxdb/releases/influxdb2-2.7.1-i386.deb
which does not exist

need to figure out, which source package will work for you... currently i ran out of time... will have a look today evening..

**Comment by Dattel** [comment]
but currently i think, you can't use these influxdb2 addon on your system because there are no i386 binarys available.

**Comment by Dattel** [comment]
Sorry mate - i can't find any precompiled debian influxDB2 package for x86/i386 to create my addon-container.. so currently i can't support these architecture.. if you find any source, let me know 

:-(

**Comment by Dattel** [comment]
What kind of hardware are you using underneath proxmox?

**Comment by Dattel** [comment]
here is some information from INFLUX about the missinig 32bit implementation.

[https://www.influxdata.com/blog/influxdb-oss-and-enterprise-roadmap-update-from-influxdays-emea/](https://www.influxdata.com/blog/influxdb-oss-and-enterprise-roadmap-update-from-influxdays-emea/)

**Comment by dorinvlas** [comment]
> What kind of hardware are you using underneath proxmox?

its a fujitsu laptop i5
root@mhub:~# dmidecode | grep -A3 '^System Information'
System Information
        Manufacturer: FUJITSU
        Product Name: LIFEBOOK E751
        Version: 10601186096

**Comment by dorinvlas** [comment]
![image](https://github.com/Dattel/homeassistant-influxdb2/assets/13332461/ab7bc07c-5208-4713-868c-0b0970ced867)
right now.

**Comment by Dattel** [comment]
yes, i removed the i386 in the latest version because it does not make sense if there is no iinflux2.deb for i386.

Why are you not using a x64 os?

**Comment by dorinvlas** [comment]
its Home Assistance OS, I do not use home assistance on top of a linux distribution.

**Comment by Dattel** [comment]
okay.. i installed a clean hassio and tried to install the addon - got the same error as you :-(

**Comment by diamant-x** [comment]
Same issue here for InfluxDB2 version 0.0.5:
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 14:41:30 (3 occurrences)
Last logged: 14:45:47

Failed to to call /addons/50fa1dca_influxdb2/install - Unknown error, see supervisor
```
Which points me to:
```
23-06-18 14:41:30 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/50fa1dca_influxdb2
23-06-18 14:41:30 ERROR (SyncWorker_5) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
23-06-18 14:41:45 ERROR (SyncWorker_0) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
```
on a RaspberryPi4 8GB with HA OS version
```
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest
```
I'm successfully running through portainer the official InfluxDBv2 container in this system, but i'm looking to migrate to a pre-built addon so that my backups include it moving forward.
Happy to provide more info to fix this.

**Comment by diamant-x** [comment]
> Happy to provide more info to fix this.

Just correcting myself, I managed to get it installed. 
The thing is I had added as repository this one https://github.com/Dattel/repository which seems to be a different one (some repos keep the addons and the 'main repo' separated so i thought that was the one).
Now I've added https://github.com/Dattel/homeassistant-influxdb2 directly as the source repo in HA addon page and installed it though that and seems to have worked.
I'll give it some time to get it running, and attempt to migrate the data from the docker standalone to this one and see where i get.

**Comment by Dattel** [comment]
thanks for the feedback... 
i have also https://github.com/Dattel/homeassistant-influxdb2 in my homeassistant as repository source.

i will have a look, what's different between the two repos. Yes indead, that was the intention, to keep a main repository separate from the plugin... Since this is my first try to provide a addon, i'm not an expert... it's more a learning by doing - hopefully with the help of some users providing me some informations... so if it's not working with ../repository keep going with ../homeassistant-influxdb2 .... but be carefull with new updates... maybe we can talk before updating your system. :-D

Currently i'm a bit dissappoited as i recognize, influxdb2 will only be provided for x64 Architectures. so i'm not sure, iif influxdb2 will find it's way to the default plugins of homeassistant. I have both variants in parall running on my system and pushing data simultaneous to both of them.. I don't yet have the courage to switch completely to influx2

**Comment by Dattel** [comment]
as i understand, the https://github.com/Dattel/repository would only work properly, if i would provide a prebuild docker
-> image: <imagepath> in config.yaml

currently it's not my intention, because is see that plugin in an early state of testing..
but I will try to update it as fast as new influx versions will be released... maybe there will be an official plugin later - but then we are ahead of time with already populated databases and working stuff around :-D

**Comment by diamant-x** [comment]
> I have both variants in parall running on my system and pushing data simultaneous to both of them.. 

How do you do that? With NodeRed? 
I tried setting up two configs of the homeassitant integration to push to both but it only works with 1 instance so i have to choose which one.

So far my standalone docker container of infludb2 is working fine for months. My biggest concern is that 1) HA OS shows up as 'unsupported' because i'm running custom containers instead of addons, and 2) i'm missing it on backups so if my SDCard fails i'll loose all my yearly historical data.

I would say 64 bit only is not an issue nowadays, but I do understand HA is meant to be possible to run in multiple devices, including old 32 bit only systems. So I agree it would look like it won't make it as an official addon due to that as well... 
In any case, I would be happy enough if its provided by you or someone else. I requested it as well to https://github.com/alexbelgium/hassio-addons/issues/715#issue-1587725618 but he's out of time at the moment to include it, but maybe you can see how he sets up different custom addons to identify a scalable way to keep up to date.

**Comment by Dattel** [comment]
Sadly, two influx-configs aren't allowed, so yes it's a simple node-red flow, which stores an explicite subset of states to influx2
![image](https://github.com/Dattel/homeassistant-influxdb2/assets/17568075/6897fef7-932d-436c-b516-a769eb572d1f)

the function will transform the data a bit:

![image](https://github.com/Dattel/homeassistant-influxdb2/assets/17568075/fd2b90bf-37ee-4790-9464-a233d3cdfc20)

So creating the repository and the plugin was in total a streight-forward process with a little bit of research... I will try to keep that running. Feel free to contribute :-D
